##Pre-requisite:You have created a volume named credVolume 
##db-secrets will be created from secrets.yml
##volume credVolume will be created from the volume definition

apiVersion: v1
kind: Pod
metadata:
  name: sec_pod
  labels:
    app: helloworld
  spec:
     containers:
       -name : k8sdemo
        image: xlr99/hello-world
        ports:
          -name: nodejs-port
           containerPort: 3000 
        
        volumeMounts:
          -name : credVolume
           mountPath: /etc/creds
           readOnly: true

        volumes:
          -name : credVolume
           secret:
             secretName : db-secrets       