##Pre-requisite:a>>   echo "sdsdf">>./username.txt  && echo "asdasd">>./password.txt

##b>>>>>>>>>>>>>>>>   k create secret generic db-secret --from-file=./username.txt --from-file=./password.txt


apiVersion: v1
kind: Pod
metadata:
  name: nodehello
  labels:
    app: hello
spec:
  containers:
    -name : k8s-demo
     image: xlr99/hello-world
     ports:
       -name: nodejs-port
        containerPort: 3000
     env:
      -name : SECRET_USERNAME
       valueFrom:
        secretKeyRef:
          name: db-secret
          key : username
      
      -name : SECRET_PASSWORD
       valueFrom:
        secretKeyRef:
          name: db-secret
          key: username

          