##Pre-requisite: You have created a configmap named app-config

apiVersion: v1
kind: Pod
metadata:
  name: some_name
  labels:
    app: hello
spec:
  containers:
    - name: k8s-demo
      image: xlr99/hello-world
      ports:
        -name: nodejs-port
         containerPort: 3000
      volumeMounts:
        - name: config-volume ##(name of the volume)
          mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: app-config ##As the property suggests,the name of the configmap file created using kubectl(Readme.md)   
                  