apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db_deployment
spec: ##replication Controller
  replicas: 3
  template:
    metadata:  
      labels:
        app: db_world
    spec:
      containers:
        - name: k8s-demo
          image: wardviaene/k8s-demo
          command: ["node", "index-db.js"]
          ports:
           - name: nodejs-port
             containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: database-service
            
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: helloworld-secrets
                  key: rootPassword

            -name: MYSQL_DATABASE
             valueFrom:
               secretKeyRef:
                 name: helloworld-secrets
                 key: database      
