apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers: 
        - name: k8s-demo
          image: xlr99/hello-world
          ports:
            - name: nodejs-port
              containerPort: 3000
---
              