apiVersion: v1

kind: Pod

metadata:
  name: nodehello
  labels:
    app: hello
  spec:
     containers:
       -name: k8's demo
        image: xlr99/hello-world
        ports:
          -containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000 
          initialDelay : 15 
          timeoutSeconds : 30   