apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ok
    spec:
      containers:
        -name : k8s-demo
         image: xlr99/hello-world
         ports:
           -containerPort: 3000
            name: somename      