apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  selector:
    app: bla
  replicas: 2
  template:   ##pod Template
    metadata:
      labels:
        app: bla
    spec:
      containers:
        -name: k8s-demo
         image: xlr99/hello-world
         ports:
           - name: nodejs-port
             containerPort: 3000

