apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    wpress: deployment ##DEPLOYMENT
spec:
  replicas: 1
  metadata:
    name: wordpress-r_set
    labels: ##REPLICA CONTROLLER
      wpress: r_set
  template:
    metadata:
      labels:  ##POD
        app: wordpress
        wpress: pod 
    spec:
      containers:
        

        -name: wordpress
         image: wordpress:4-php7.0
         ports:
           -name: http-port
            containerPort: 80
         env:
           -name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: wordpress-secrets
                 key: db-password

            -name: WORDPRESS_DB_HOST
             value: 127.0.0.1

        -name : mysql
         image: mysql:5.7
         ports:
           -name: mysql-port
            containerPort: 3306

         env:
           -name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db-password

